protected/models/ContactForm.php
<?php

class ContactForm extends CFormModel
{
	public $name;
	public $email;
	public $subject;
	public $message;

	public function rules()
	{
		return array(
			array('name, email, subject, message', 'required'),
			array('email', 'email'),
		);
	}

	public function attributeLabels()
	{
		return array(
			'name' => 'Nome',
			'email' => 'E-mail',
			'subject' => 'Assunto',
			'message' => 'Mensagem',
		);
	}

	public function getSubjectOptions()
	{
		return array(
			1 => 'Dúvidas',
			2 => 'Sugestões',
			3 => 'Envio de Currículo',
		);
	}

	public function process()
	{
		$message = new YiiMailMessage;
		$message->setTo(Yii::app()->params['mail.senderEmail']);
		$message->setFrom(Yii::app()->params['mail.senderEmail']);
		$message->setReplyTo($this->email);
		$body = Yii::app()->controller->renderPartial(
			'application.views.mail.internal.contact', 
			array('contactForm' => $this, 'message' => $message), true
		);	
		$message->setBody(array('message' => $message, 'content' => $body), 'text/html');

		if (!Yii::app()->mail->send($message)) {
			$this->addError(null, 'Erro inesperado ao enviar a mensagem, por favor, tente novamente mais tarde.');
			return false;
		} else
			return true;
	}
}

protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
	public function actionIndex() 
	{
		$this->render('index');
	}

	public function actionProducts($category = null, $id = null) 
	{
		$categories = $this->productCategories;

		if ($category === null)
			$this->redirect(array('products', 'category' => $this->currentProductCategory->alias));

		foreach ($categories as $item) {
			if ($item->alias == $category) {
				$currentCategory = $item;
				break;
			}
		}

		if (empty($currentCategory)) {
			$currentCategory = Category::model()->findByAttributes(array('alias' => $category));

			if ($currentCategory === null)
				throw new CHttpException(404, 'Página não encontrada.');
		} else
			$this->currentProductCategory = $currentCategory;

		$products = $currentCategory->products;

		$this->render('products', array(
			'currentCategory' => $currentCategory,
			'categories' => $categories, 
			'products' => $products, 
		));
	}

	public function actionAbout() 
	{
		$this->render('about');
	}

	public function actionFaq() 
	{
		$this->render('faq', array('tips' => Tip::model()->published()->findAll()));
	}

	public function actionContact() 
	{
		$contactForm = new ContactForm;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'contactForm') {
			echo CActiveForm::validate($contactForm);
			Yii::app()->end();
		}
		
		if (isset($_POST['ContactForm'])) {
			$contactForm->attributes = $_POST['ContactForm'];

			if ($contactForm->validate() && $contactForm->process()) {
				Yii::app()->user->setAlert(WebUser::ALERT_SUCCESS, 'Seu solicitação foi enviado com sucesso. Por favor, aguarde nosso contato.');

				if (isset($_POST['returnUrl']))
					$this->redirect($_POST['returnUrl']);
				else
					$this->redirect(array('index'));
			} else
				Yii::app()->user->setAlert(WebUser::ALERT_DANGER, current(current($contactForm->getErrors())));
		}

		$this->render('contact', array('contactForm' => $contactForm));
	}

	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

protected/views/home/_aboutHeaderCover.php
<div class="mn-cover-bg" style="background-image: url('<?php echo APP_IMG_URL; ?>/main-header-cover-about.jpg');"></div>

<?php 
$css = <<<CSS
.mn-main-brand {
	display: none;
}
CSS;
Yii::app()->clientScript->registerCss('home._aboutHeaderCover', $css);

protected/views/home/_contactHeaderCover.php
<div class="mn-cover-bg" style="background-image: url('<?php echo APP_IMG_URL; ?>/main-header-cover-contact.jpg');"></div>
<div class="mn-map mn-cover-bg" id="mn-map" data-lat="<?php echo Yii::app()->params['map.lat']; ?>" data-lng="<?php echo Yii::app()->params['map.lng']; ?>"></div>

protected/views/home/_faqHeaderCover.php
<div class="mn-cover-bg" style="background-image: url('<?php echo APP_IMG_URL; ?>/main-header-cover-faq.jpg');"></div>

protected/views/home/_showroom.php
<div class="mn-showroom uk-slidenav-position" data-uk-slideshow="{start:<?php echo $currentProductCategoryIndex; ?>, autoplay:true}">
    <ul class="uk-slideshow">

        <?php foreach ($productCategories as $i => $category) : ?> 

        <li<?php echo $currentProductCategoryIndex == $i ? ' class="uk-active"' : ''; ?> style="background-image: url('<?php echo APP_IMG_URL . '/covers/category-' . $category->alias . '.jpg'; ?>');">
            <div class="mn-showroom-content">
                <h1 class="mn-showroom-title"><?php echo CHtml::encode($category->name); ?></h1>
                <p><?php echo CHtml::encode($category->description); ?></p>
                <a class="uk-button uk-button-glass" href="<?php echo $this->createUrl('home/products', array('category' => $category->alias)); ?>">Mais <?php echo CHtml::encode($category->name); ?></a>
            </div>
        </li>

        <?php endforeach; ?>

    </ul>

    <?php echo $this->renderPartial('_showroomNav', array(
        'productCategories' => $productCategories, 
        'currentProductCategory' => $currentProductCategory,
        'currentProductCategoryIndex' => $currentProductCategoryIndex,
    )); ?>   
    
</div>

protected/views/home/_showroomNav.php
<ul class="mn-showroom-nav">
	<?php foreach ($productCategories as $i => $category) : ?> 

	<li<?php echo $i == $currentProductCategoryIndex ? ' class="uk-active"' : ''; ?> data-uk-slideshow-item="<?php echo $i; ?>">
		<a href="<?php echo $this->createUrl('home/products', array('category' => $category->alias)); ?>" title="<?php echo CHtml::encode($category->name); ?>"  data-uk-tooltip style="background-image: url('<?php echo $category->getImage('small')->url; ?>');">
			<div class="uk-overlay">
				<div class="uk-overlay-area">
					<div class="uk-overlay-area-content">
						<h3 class="mn-showroom-nav-title"><?php echo CHtml::encode($category->name); ?></h3>
					</div>
				</div>
			</div>
		</a>
	</li>

	<?php endforeach; ?>
</ul>

protected/views/home/about.php
<?php 
$this->pageTitle = 'Sobre';
$this->mainAlt = true;
$this->mainTitle = 'A Espaço Design';
$this->mainHeaderCover = $this->renderPartial('_aboutHeaderCover', null, true);
?>

<div class="uk-grid uk-text-justify" data-uk-grid-margin>
    <div class="uk-width-1-1 uk-width-medium-1-2">
        <p>Espaço Design reconhecida pela sua qualidade em móveis planejados, conta com um know-how de 10 anos de mercado. Uma marca que oferece aos seus clientes o que há de mais atual em design e decoração.</p>
        <p>Com sua experiência, a Espaço Design sabe que cada cliente tem sua necessidade exclusiva, por isso valoriza em todos seus projetos a identidade e a expectativa de cada cliente. Proporcionando assim não apenas móveis, mas ambientes aconchegantes, exclusivos e funcionais.</p>
    </div>
    <div class="uk-width-1-1 uk-width-medium-1-2">
        <p>A Espaço Design trabalha com matéria-prima ecologicamente correta, garantia e prazo de entrega combinado em contrato. Desta forma, garante total satisfação aos seus clientes, através de um atendimento diferenciado e ideias inovadoras, proporcionando ambientes residenciais ou comerciais de bom gosto e com o melhor aproveitamento do espaço.</p>
        <p>Tome um café com o pessoal da Espaço Design e fale sobre o seu projeto, você irá se surpreender com as soluções que poderão ajudar você a realizar seu sonho.</p>
    </div>
</div>      

protected/views/home/contact.php
<?php 
$this->mainAlt = true;
$this->pageTitle = 'Contato';
$this->mainTitle = 'Fale Conosco';
$this->mainHeaderCover = $this->renderPartial('_contactHeaderCover', null, true);
?>

<p>Venha tomar um café conosco, teremos muito prazer em poder ouvir a sua ideia.</p>		
<p class="uk-margin-large-bottom">
	Rua Rui Barbosa, 1553, Centro, CEP: 13320-230 - Salto/SP<br>
	<strong>Telefone: <?php echo CHtml::encode(Yii::app()->params['biz.phone']); ?></strong> &ndash; <strong>Celular: <?php echo CHtml::encode(Yii::app()->params['biz.mobile']); ?></strong>
</p>

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'contactForm',
	'enableAjaxValidation' => true,
	'enableClientValidation' => true,
	'htmlOptions' => array(
		'class' => 'uk-form uk-form-stacked',
	),
	'clientOptions' => array(
		'validateOnSubmit' => true,
	),
)); ?>

<div class="uk-grid uk-grid-small uk-text-center" data-uk-grid-margin>
	<div class="uk-width-1-1">
		<?php echo $form->dropDownList($contactForm, 'subject', $contactForm->subjectOptions, array('class' => 'uk-width-1-1 uk-form-large')); ?>
		<?php echo $form->error($contactForm, 'subject', array('class' => 'uk-text-danger uk-text-small uk-text-bold uk-text-italic uk-margin-small-top')); ?>
	</div>
	<div class="uk-width-1-1 uk-width-medium-1-2">
		<?php echo $form->textField($contactForm, 'name', array('class' => 'uk-width-1-1 uk-form-large', 'placeholder' => $contactForm->getAttributeLabel('name'))); ?>
		<?php echo $form->error($contactForm, 'name', array('class' => 'uk-text-danger uk-text-small uk-text-bold uk-text-italic uk-margin-small-top')); ?>
	</div>				
	<div class="uk-width-1-1 uk-width-medium-1-2">
		<?php echo $form->textField($contactForm, 'email', array('class' => 'uk-width-1-1 uk-form-large', 'placeholder' => $contactForm->getAttributeLabel('email'))); ?>
		<?php echo $form->error($contactForm, 'email', array('class' => 'uk-text-danger uk-text-small uk-text-bold uk-text-italic uk-margin-small-top')); ?>
	</div>					
	<div class="uk-width-1-1">
		<?php echo $form->textArea($contactForm, 'message', array('class' => 'uk-width-1-1 uk-form-large', 'placeholder' => $contactForm->getAttributeLabel('message'), 'rows' => 4)); ?>
		<?php echo $form->error($contactForm, 'message', array('class' => 'uk-text-danger uk-text-small uk-text-bold uk-text-italic uk-margin-small-top')); ?>
	</div>
	<div class="uk-width-1-1">
		<button type="submit" class="uk-button uk-button-primary uk-button-large"><i class="uk-icon-check"></i> Enviar</button>
	</div>
</div>		
 
<?php $this->endWidget(); ?>

protected/views/home/error.php
<?php $this->pageTitle = 'Erro ' . $code; ?>

<p class="alert alert-error text-center"><?php echo CHtml::encode($message); ?></p> 

protected/views/home/faq.php
<?php 
$this->pageTitle = 'Dicas';
$this->mainAlt = true;
$this->mainTitle = 'Perguntas Frequentes';
$this->mainHeaderCover = $this->renderPartial('_faqHeaderCover', null, true);
?>

<p class="uk-margin-large-bottom">Abaixo estão algumas perguntas frequentes, caso tenha mais dúvidas por favor entre em contato.</p>

<div class="uk-accordion uk-grid uk-text-left" data-uk-accordion>
	<?php foreach ($tips as $tip) : ?>
	
	<div class="uk-width-1-2">
	  <h3 class="uk-accordion-title"><i class="uk-icon-plus-minus uk-icon-bordered"></i> <?php echo CHtml::encode($tip->title); ?></h3>
	  <div class="uk-accordion-content"><?php echo $tip->content; ?></div>
	</div>

  <?php endforeach; ?>
</div>

protected/views/home/index.php
<?php 
$this->pageTitle = 'Bem-vindo';
$this->fullscreen = true;
?>

<?php echo $this->renderPartial('/home/_showroom', array(
	'productCategories' => $this->productCategories, 
	'currentProductCategory' => $this->currentProductCategory,
	'currentProductCategoryIndex' => $this->currentProductCategoryIndex,
)); ?> 

protected/views/home/products.php
<?php 
$this->pageTitle = $currentCategory->name;
?>

<div class="uk-grid" data-uk-grid-margin>

	<?php foreach ($products as $product) : ?>

	<div class="uk-width-small-1-2 uk-width-large-1-3">
		<div class="mn-cover mn-cover-bg mn-cover-16by9 uk-overlay" style="background-image: url('<?php echo $product->getImage('small')->url; ?>');">    
	
			<img src="<?php echo $product->getImage('small')->url; ?>" alt="<?php echo CHtml::encode($product->name); ?>">

			<div class="uk-overlay-area">
				<div class="uk-overlay-area-content">
					<h3><?php echo CHtml::encode($product->name); ?></h3>			
					<?php if ($product->manufacturer) : ?>
					<p><strong>Fabricante:</strong> <?php echo CHtml::encode($product->manufacturer->name); ?></p>
					<?php endif; ?>
					<?php echo $product->description; ?>
					<a class="uk-button uk-button-glass" href="<?php echo $product->getImage('large')->url; ?>"  title="<?php echo CHtml::encode($product->name); ?>" data-uk-lightbox="{group:'product'}"><i class="uk-icon-search"></i></a>
				</div>
			</div>                                   
		</div>
	</div>

	<?php endforeach; ?>

</div>       

protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="pt-br" class="<?php echo 'pg-' . $this->id . '-' . $this->action->id . ($this->fullscreen ? ' mn-fullscreen' : ''); ?>">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="<?php echo CHtml::encode(Yii::app()->params['site.description']); ?>">
		<meta name="keywords" content="<?php echo CHtml::encode(Yii::app()->params['site.keywords']); ?>">

		<title><?php echo CHtml::encode(($this->pageTitle ? $this->pageTitle . ' - ' : null) . Yii::app()->params['site.name']); ?></title>

		<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/uikit.css'); ?>
		<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/main.css'); ?>	

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<link href="http://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
		<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300,300italic,400,400italic,700,700italic" rel="stylesheet">
	</head>
	<body>

		<div class="mn-wrapper">
			<div class="mn-cover-bg" style="background-image: url('<?php echo APP_IMG_URL . '/covers/category-' . $this->currentProductCategory->alias . (!$this->fullscreen ? '-blur' : '') . '.jpg'; ?>')"></div>

			<header class="mn-header uk-clearfix">
				<div class="mn-header-offcanvas-toggle uk-hidden-large">
					<a class="uk-icon-button uk-icon-bars" href="#offcanvas" data-uk-offcanvas></a>
				</div>
				<nav class="mn-header-nav uk-visible-large">
					<ul>
						<li<?php echo $this->id === 'home' && $this->action->id === 'index' ? ' class="mn-active"' : '' ?>>
							<a href="<?php echo Yii::app()->homeUrl; ?>">Home</a>
						</li>
						<li<?php echo $this->id === 'home' && $this->action->id === 'products' ? ' class="mn-active"' : '' ?>>
							<a href="<?php echo Yii::app()->createUrl('/home/products'); ?>">Ambientes</a>
						</li>
						<li<?php echo $this->id === 'home' && $this->action->id === 'about' ? ' class="mn-active"' : '' ?>>
							<a href="<?php echo Yii::app()->createUrl('/home/about'); ?>">Sobre</a>
						</li>
						<li<?php echo $this->id === 'home' && $this->action->id === 'faq' ? ' class="mn-active"' : '' ?>>
							<a href="<?php echo Yii::app()->createUrl('/home/faq'); ?>">Dicas</a>
						</li>
						<li<?php echo $this->id === 'home' && $this->action->id === 'contact' ? ' class="mn-active"' : '' ?>>
							<a href="<?php echo Yii::app()->createUrl('/home/contact'); ?>">Contato</a>
						</li>
					</ul>                
				</nav>
			</header>


			<main class="mn-body uk-clearfix">

				<?php if (!$this->mainAlt) : ?>
				
				<div class="mn-top">
					<a class="mn-brand" href="<?php echo Yii::app()->homeUrl; ?>">
						<img src="<?php echo APP_IMG_URL; ?>/logo.png" alt="<?php echo CHtml::encode(Yii::app()->params['site.name']); ?>">
					</a>
				</div>

				<?php endif; ?>
				
				<div class="<?php echo $this->mainAlt ? 'mn-main-alt' : 'mn-main'; ?>">

					<?php if ($this->fullscreen) : ?>

					<?php echo $content; ?>

					<?php else : ?>

					<a class="mn-main-brand mn-brand mn-brand-compact" href="<?php echo Yii::app()->homeUrl; ?>">
						<img src="<?php echo APP_IMG_URL; ?>/logo-compact.png" alt="<?php echo CHtml::encode(Yii::app()->params['site.name']); ?>">
					</a>
					<a class="mn-main-close mn-close" href="<?php echo Yii::app()->homeUrl; ?>"></a>
					<header class="mn-main-header">
						<div class="uk-container uk-container-center">

							<?php if ($this->mainHeaderCover) : ?>

							<div class="mn-main-cover mn-cover">
								<?php echo $this->mainHeaderCover; ?>
							</div>

							<?php endif; ?>

							<h1 class="mn-main-header-title"><?php echo $this->mainTitle ? $this->mainTitle : CHtml::encode($this->pageTitle); ?></h1>  

							<?php if ($this->id == 'home' && $this->action->id == 'products') : ?>

							<nav class="mn-main-header-nav uk-visible-large">
								<ul>

									<?php foreach ($this->productCategories as $i => $category) : ?> 

									<li<?php echo $this->currentProductCategoryIndex == $i ? ' class="mn-active"' : ''; ?>>
										<a href="<?php echo $this->createUrl('/home/products', array('category' => $category->alias)); ?>"><?php echo CHtml::encode($category->name); ?></a>
									</li>

									<?php endforeach; ?>

								</ul>
							</nav>			

							<?php endif; ?>

						</div>
					</header>
					<div class="mn-main-body">
						<div class="uk-container uk-container-center">
							
							<?php echo $content; ?>

						</div>
					</div>

					<?php endif; ?>

				</div>

				<?php if (!$this->mainAlt) : ?>

				<div class="mn-bottom">               
					<h2 class="mn-bottom-title">Ambientes</h2>
					<?php echo $this->renderPartial('/home/_showroomNav', array(
						'productCategories' => $this->productCategories, 
						'currentProductCategory' => $this->currentProductCategory, 
						'currentProductCategoryIndex' => $this->currentProductCategoryIndex,
					)); ?>   
				</div>

				<?php endif; ?>
			</main>


			<footer class="mn-footer uk-clearfix">
				<div class="uk-container uk-container-center">
						<div class="mn-row">
							<div class="mn-col mn-col-a">Fale conosco: <?php echo CHtml::encode(Yii::app()->params['biz.phone'] . (Yii::app()->params['biz.mobile'] ? ' / ' . Yii::app()->params['biz.mobile'] : '')); ?></div>
							<div class="mn-col mn-col-b">
								<?php if (Yii::app()->params['facebook.url']) : ?>
									<a class="uk-icon-button uk-icon-button-glass uk-icon-facebook uk-margin-left uk-margin-right" href="<?php echo Yii::app()->params['facebook.url']; ?>" target="_blank"></a>
								<?php endif; ?>
							</div>
							<div class="mn-col mn-col-c">&copy; <?php echo date('Y'); ?>. <?php echo CHtml::encode(Yii::app()->params['biz.name']); ?>.</div>
						</div>
				</div>
			</footer>   
		</div>

		<div id="offcanvas" class="uk-offcanvas">
			<div class="uk-offcanvas-bar uk-offcanvas-bar-flip">
				<ul class="uk-nav uk-nav-offcanvas">
					<li><a href="<?php echo Yii::app()->homeUrl; ?>">Home</a></li>
					<li>
						<a href="<?php echo Yii::app()->createUrl('/home/products'); ?>">Ambientes</a>
						<div>
							<ul class="uk-nav-sub">
								<?php foreach ($this->productCategories as $i => $category) : ?> 

								<li><a href="<?php echo $this->createUrl('/home/products', array('category' => $category->alias)); ?>"><?php echo CHtml::encode($category->name); ?></a></li>

								<?php endforeach; ?>
							</ul>
						</div>
					</li>
					<li><a href="<?php echo Yii::app()->createUrl('home/about'); ?>">Sobre</a></li>
					<li><a href="<?php echo Yii::app()->createUrl('home/faq'); ?>">Dicas</a></li>
					<li><a href="<?php echo Yii::app()->createUrl('home/contact'); ?>">Contato</a></li>
				</ul>
			</div>
		</div>


		<div class="mn-flahes">
			<ul>
				<!--[if lt IE 9]>
				<li class="uk-text-danger"><i class="uk-icon-times-circle"></i> Você está usando um navegador <strong>desatualizado</strong>. Por favor, atualize seu navegador para melhorar sua experiência.</li>
				<![endif]-->

				<noscript>
				<li class="uk-text-danger"><i class="uk-icon-times-circle"></i> Por favor, ative o javascript no seu navegador.</li>
				</noscript>

				<?php if ($alert = Yii::app()->user->getAlert(WebUser::ALERT_SUCCESS)) : ?>
			
				<li class="uk-text-success"><i class="uk-icon-check-circle"></i> <strong>Sucesso!</strong> <?php echo $alert; ?></li>
			
				<?php endif; ?>

				<?php if ($alert = Yii::app()->user->getAlert(WebUser::ALERT_INFO)) : ?>
			
				<li class="uk-text-info"><i class="uk-icon-exclamation-circle"></i> <strong>Info!</strong> <?php echo $alert; ?></li>
			
				<?php endif; ?>

				<?php if ($alert = Yii::app()->user->getAlert(WebUser::ALERT_WARNING)) : ?>
			
				<li class="uk-text-warning"><i class="uk-icon-exclamation-circle"></i> <strong>Atencão!</strong> <?php echo $alert; ?></li>
			
				<?php endif; ?>

				<?php if ($alert = Yii::app()->user->getAlert(WebUser::ALERT_DANGER)) : ?>
			
				<li class="uk-text-danger"><i class="uk-icon-times-circle"></i> <strong>Ops. Algo deu errado.</strong> <?php echo $alert; ?></li>

				<?php endif; ?>
			</ul>
		</div>


		<?php if (Yii::app()->params['ga.trackingId']) : ?>

		<script>
		var _gaq=[['_setAccount','<?php echo Yii::app()->params['ga.trackingId'] ?>'],['_trackPageview']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src='//www.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
		</script>

		<?php endif; ?>

		<?php Yii::app()->clientScript->registerCoreScript('jquery', CClientScript::POS_END); ?>
		<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/vendor/uikit/dist/js/uikit.min.js', CClientScript::POS_END); ?>
		<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/vendor/uikit/dist/js/components/lightbox.min.js', CClientScript::POS_END); ?>
		<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/vendor/uikit/dist/js/components/slideshow.min.js', CClientScript::POS_END); ?>
		<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/vendor/uikit/dist/js/components/accordion.min.js', CClientScript::POS_END); ?>
		<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/main.js', CClientScript::POS_END); ?>
		
	</body>
</html>