admin/protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{		
	public $searchForm = true;
	
	public function actionIndex($belongsTo, $s = null)
	{
		$model = new Category('search');
		$model->unsetAttributes();

		if ($belongsTo !== 'Product' && $belongsTo !== 'Post')
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');

		$model->belongs_to = $belongsTo;
			
		if (isset($_GET['Category']))
			$model->setAttributes($_GET['Category']);
		else 
			$model->s = $s;
		
		$this->render('index', array('model' => $model));
	}
	
	public function actionCreate($belongsTo)
	{
		$model = new Category;

		if ($belongsTo !== 'Product' && $belongsTo !== 'Post')
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');

		$model->belongs_to = $belongsTo;

		if (isset($_POST['Category'])) {
			$model->setAttributes($_POST['Category']);
			$img = CUploadedFile::getInstance($model, 'img');
			$model->img = $img ? $img : $model->img;

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->redirect(array('update', 'id' => $model->id));
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel('Category');

		if (isset($_POST['Category'])) {
			$model->setAttributes($_POST['Category']);
			$img = CUploadedFile::getInstance($model, 'img');
			$model->img = $img ? $img : $model->img;

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->refresh();
			}
		}

		$this->render('update', array('model' => $model));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			$this->loadModel('Category', $id)->delete();

			if (!Yii::app()->request->isAjaxRequest) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> O registro foi excluído com sucesso.');		

				$this->redirect(array('index'));
			}
		} else
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');
	}
}

admin/protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
	public function actionIndex()
	{
		$this->redirect(Yii::app()->createUrl('/product'));
	}
		
	public function actionLogin()
	{
		$model = new LoginForm;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'loginForm') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			if ($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		
		$this->render('login', array('model' => $model));
	}
	
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

admin/protected/controllers/UserController.php
<?php

class UserController extends Controller
{	
	public $searchForm = true;
		
	public function accessRules()
	{
		return CMap::mergeArray(array(
			array(
				'allow',
				'actions' => array('profile'),
				'users' => array('@'),
			),
		), parent::accessRules());
	}
	
	public function actionIndex($s = null)
	{
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User']))
			$model->setAttributes($_GET['User']);
		else 
			$model->s = $s;
		
		$this->render('index', array('model' => $model));
	}
	
	public function actionCreate()
	{
		$model = new User;

		if(isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->redirect(array('update', 'id' => $model->id));
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel('User');

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->refresh();
			}
		}

		$this->render('update', array('model' => $model));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel('User', $id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!Yii::app()->request->isAjaxRequest) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> O registro foi excluído com sucesso.');	

				$this->redirect(array('index'));
			}
		} else
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');
	}

	public function actionProfile()
	{
		$model = $this->loadModel('User', Yii::app()->user->id);

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->redirect(Yii::app()->homeUrl);
			}
		}

		$this->render('profile', array('model' => $model));
	}
}

admin/protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="pt-br" />
	<title><?php echo Yii::app()->name; ?> | <?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/bootstrap.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/bootstrap-responsive.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/main.css'); ?>	

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body class="ctrl-<?php echo $this->id . ' act-' . $this->action->id; ?>">
	
<?php if (!Yii::app()->user->isGuest) : ?>
	
<?php $this->widget('bootstrap.widgets.TbNavbar', array(
	'brandLabel' => CHtml::encode(Yii::app()->name),
	'brandUrl' => Yii::app()->createUrl('home/index'),
	'color' => TbHtml::NAVBAR_COLOR_INVERSE,
	'collapse' => true,
	'items' => array(
		Yii::app()->user->is('admin') ? array(
			'class' => 'bootstrap.widgets.TbNav',
			'items' => array(
				array(
					'label' => 'Produtos',
					'url' => array('/product'),
				),
				array(
					'label' => 'Dúvidas Frequentes',
					'url' => array('/tip'),
				),
				array(
					'label' => 'Usuários',
					'url' => array('/user'),
				),
			),
		) : array(),	
		array(
			'class' => 'bootstrap.widgets.TbNav',
			'htmlOptions' => array('class' => 'pull-right'),
			'items' => array(
				array(
					'icon' => TbHtml::ICON_USER,
					'label' => Yii::app()->user->name,
					'items' => array(
						array(
							'label' => 'Perfil',
							'icon' => TbHtml::ICON_USER,
							'url' => array('/user/profile', 'id' => Yii::app()->user->id),
						),
						TbHtml::menuDivider(),						
						array(
							'label' => 'Sair',
							'icon' => TbHtml::ICON_OFF,
							'url' => array('/home/logout'),
						),						
					),
				),
			),
		),
		Yii::app()->user->is('root') ? array(
			'class' => 'bootstrap.widgets.TbNav',
			'htmlOptions' => array('class' => 'pull-right'),
			'items' => array(
				array(
					'icon' => TbHtml::ICON_COG,
					'items' => array(
						array(
							'label' => 'Categorias de Produtos',
							'url' => array('/category/index', 'belongsTo' => 'Product'),
						),						
					),
				),
			),
		) : array(),
	),
)); ?>
	
<div id="header">
	<div class="container">
		<h2 class="title">
			<?php echo $this->pageTitle; ?>
			<small><?php echo $this->pageSubtitle; ?></small>
		</h2>
		<?php if ($this->searchForm || $this->menu) : ?>		
		<div class="toolbar">
			<?php if ($this->searchForm) {
				echo TbHtml::beginFormTb(TbHtml::FORM_LAYOUT_SEARCH, $this->createUrl('index', $this->searchParams), 'get');
				echo TbHtml::textField('s', Yii::app()->request->getParam('s'), 
					array('class' => 'search-query', 'placeholder' => 'Pesquisar', 'autocomplete' => 'false'));
				echo TbHtml::submitButton(TbHtml::icon(TbHtml::ICON_SEARCH, array('color' => TbHtml::ICON_COLOR_WHITE)), 
					array('color' => TbHtml::BUTTON_COLOR_LINK, 'name' => false));
				echo TbHtml::endForm();
			} 
			foreach ($this->menu as $items) {
				foreach ($items as $i => $item) {
					$items[$i]['title'] = $items[$i]['label'];
					$items[$i]['rel'] = 'tooltip';
					$items[$i]['label'] = '';
				}
				echo TbHtml::buttonToolbar(array(array(
					'items' => $items, 
					'color' => TbHtml::BUTTON_COLOR_INVERSE, 
				)));
			} ?>
		</div>
		<?php endif; ?>
	</div>
</div>

<?php endif; ?>

<div id="content">
	<div class="container">
		<?php $this->widget('bootstrap.widgets.TbAlert'); ?>
		<?php echo $content; ?>
	</div>
</div>

<div id="footer">
	<div class="container">
		<p>Copyright &copy; <?php echo CHtml::encode(Yii::app()->name); ?>. Todos os direitos reservados.</p>
	</div>
</div>

<div id="ajax-loading"></div>

<?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/main.js', CClientScript::POS_END); ?>

</body>
</html>